version: "2.1"

services:
  hvac:
    build: .
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.sysfs: "1"
      io.balena.features.kernel-modules: "1"
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/i2c/1:/dev/i2c/1"
      - "/var/run:/var/run"
      - "/sys/kernel/debug:/sys/kernel/debug"
    cap_add:
      - SYS_RAWIO
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
      FAN_OUT: "18"
      HEATING_OUT: "23"
      BME280_I2C_BUS: "1"
      BME280_I2C_ADDRESS: "0x76"
      TEMP_UPPER_THRESHOLD: "65"
      TEMP_LOWER_THRESHOLD: "60"
      DEW_POINT_UPPER_MARGIN: "15"
      DEW_POINT_LOWER_MARGIN: "10"
    privileged: true
