FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:16-bullseye-run

RUN apt-get update && apt-get upgrade

RUN install_packages

WORKDIR /app

COPY package*.json ./
RUN npm install --only=production

COPY hvac.js .

CMD ["npm", "start" ]
