FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3-bullseye-run

RUN apt-get update && apt-get upgrade

RUN install_packages

WORKDIR /app

COPY requirements.txt .
ENV CFLAGS=-fcommon
RUN pip3 install -r requirements.txt

COPY hvac.py .

CMD ["python3", "hvac.py" ]
