version: "2.1"

services:
  hvac:
    build: .
    labels:
      io.balena.features.dbus: "1"
      io.balena.features.sysfs: "1"
      io.balena.features.kernel-modules: "1"
    devices:
      - "/dev/mem:/dev/mem"
      - "/dev/gpiomem:/dev/gpiomem"
    cap_add:
      - SYS_RAWIO
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
    privileged: true
